In [3]:

# numpy tricks 

import numpy as np
a=np.random.randint(1,50,12)
b=np.random.randint(1,12,16).reshape(4,4)


a


array([46, 12, 22,  4, 25, 14, 17, 27, 47, 14, 41, 41])

In [5]:
b

array([[10, 10,  7, 10],
       [11,  9,  5,  3],
       [10,  4,  7,  4],
       [ 5,  5,  1,  1]])

In [7]:
np.sort(a)

array([ 4, 12, 14, 14, 17, 22, 25, 27, 41, 41, 46, 47])

In [15]:
np.sort(b)  # row wise sorted

array([[ 7, 10, 10, 10],
       [ 3,  5,  9, 11],
       [ 4,  4,  7, 10],
       [ 1,  1,  5,  5]])

In [19]:
np.sort(b,axis=0)  # column wise sort

array([[ 5,  4,  1,  1],
       [10,  5,  5,  3],
       [10,  9,  7,  4],
       [11, 10,  7, 10]])

In [29]:

np.sort(b,axis=0)

array([[ 5,  4,  1,  1],
       [10,  5,  5,  3],
       [10,  9,  7,  4],
       [11, 10,  7, 10]])

In [23]:
np.sort(b,axis=0)[::-1]   # descending case


array([[11, 10,  7, 10],
       [10,  9,  7,  4],
       [10,  5,  5,  3],
       [ 5,  4,  1,  1]])

In [31]:


#np.append()

np.append(a,3)

array([46, 12, 22,  4, 25, 14, 17, 27, 47, 14, 41, 41,  3])

In [7]:


# concatenate 
import numpy as np
a=np.arange(6).reshape(2,3)
b=np.arange(6).reshape(2,3)

np.concatenate((a,b),axis=0)




array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [9]:
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [11]:

#np.unique
a=np.array([1,1,2,2,3,3,4,5,6,6,7,8,89,0])
np.unique(a)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 89])

In [15]:


#np.expand_dims()
# change the shape only not data 
# here axis work as row and column change as 0 and 1 but opposite in concatenate 

np.expand_dims(a,axis=1)

array([[ 1],
       [ 1],
       [ 2],
       [ 2],
       [ 3],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 6],
       [ 7],
       [ 8],
       [89],
       [ 0]])

In [17]:

np.expand_dims(a,axis=0)

array([[ 1,  1,  2,  2,  3,  3,  4,  5,  6,  6,  7,  8, 89,  0]])

In [21]:


#np.where()
# find the indices position greater than 50
a=np.array([1,1,2,2,3,3,4,5,6,6,7,8,89,0])
np.where(a>50)

(array([12], dtype=int64),)

In [27]:
# replace the value with 0 if it is grerater than 50

# np.where(condition,true,false)

np.where(a>50,0,a)




array([1, 1, 2, 2, 3, 3, 4, 5, 6, 6, 7, 8, 0, 0])

In [29]:
np.where(a%2==0,0,a)

array([ 1,  1,  0,  0,  3,  3,  0,  5,  0,  0,  7,  0, 89,  0])

In [31]:


#np.argmax()
np.argmax(a)

12

In [35]:
b=np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
np.argmax(b,axis=0)

array([1, 1, 1], dtype=int64)

In [39]:
np.argmax(b,axis=1)

array([2, 2], dtype=int64)

In [41]:


# np.argmin()

# same as argmax

np.argmin(a)

13

In [43]:
#np.cumsum()

np.cumsum(a)

array([  1,   2,   4,   6,   9,  12,  16,  21,  27,  33,  40,  48, 137,
       137])

In [45]:


np.cumsum(b,axis=0)




array([[0, 1, 2],
       [3, 5, 7]])

In [47]:

#np.cumprod
np.cumprod(a)


array([        1,         1,         2,         4,        12,        36,
             144,       720,      4320,     25920,    181440,   1451520,
       129185280,         0])

In [5]:

#np.percentile 
import numpy as np
a=np.array([1,1,2,2,3,3,4,5,6,6,7,8,89,0])
np.percentile(a,100) # here 100 represents the maximum 


89.0

In [7]:
np.percentile(a,0)

0.0

In [9]:
np.percentile(a,50)

3.5

In [11]:
np.median(a)

3.5

In [15]:
#np.histogram

np.histogram(a,bins=[0,20,40,60,80,100])

(array([13,  0,  0,  0,  1], dtype=int64),
 array([  0,  20,  40,  60,  80, 100]))

In [19]:



# np.corrcoef
experience=np.array([0,1,2,3,4,5,6,7,8])
salary=np.array([10000,20000,40000,50000,80000,90000,100000,110000,120000])
np.corrcoef(experience,salary)

array([[1.        , 0.98931795],
       [0.98931795, 1.        ]])

In [23]:



#np.isin

e=[0,1,3,5,7,89,4,6,76,87]
np.isin(a,e)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True])

In [25]:
a[np.isin(a,e)]

array([ 1,  1,  3,  3,  4,  5,  6,  6,  7, 89,  0])

In [27]:


#np.flip

np.flip(a)

array([ 0, 89,  8,  7,  6,  6,  5,  4,  3,  3,  2,  2,  1,  1])

In [31]:


b=np.random.randint(1,12,16).reshape(4,4)
b

array([[ 7,  7,  9, 11],
       [ 7, 10,  1,  9],
       [ 4,  7,  7,  9],
       [ 2,  4,  8,  4]])

In [33]:
np.flip(b,axis=1)

array([[11,  9,  7,  7],
       [ 9,  1, 10,  7],
       [ 9,  7,  7,  4],
       [ 4,  8,  4,  2]])

In [43]:


#np.put

np.put(a,[0,11],[100,100])
a

array([100,   1,   2,   2,   3,   3,   4,   5,   6,   6,   7, 100,  89,
         0])

In [45]:


# np.delete
np.delete(a,[2,5])

array([100,   1,   2,   3,   4,   5,   6,   6,   7, 100,  89,   0])

In [49]:



# set functions

#union
n=np.array([1,2,3,4,5,6,8])
p=np.array([3,4,5,6,7,8,9])
np.union1d(n,p)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:

# intersection
np.intersect1d(n,p)

array([3, 4, 5, 6, 8])

In [53]:


# set difference
np.setdiff1d(n,p)

array([1, 2])

In [55]:
np.setdiff1d(p,n)

array([7, 9])

In [57]:

#xor
np.setxor1d(n,p)


array([1, 2, 7, 9])

In [63]:

# setin

np.in1d(n,[1,2,3])

array([ True,  True,  True, False, False, False, False])

In [73]:
#np.clip


# most imp
print(n)
np.clip(n,a_min=3,a_max=4)

[1 2 3 4 5 6 8]


array([3, 3, 3, 4, 4, 4, 4])