In [1]:
# numpy


# creating numpy arrays 

import numpy as np
a=np.array([1,2,3,4])
print(a)

print(type(a))



# its a one dimensional array also called  vector.

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:







# 2D also called matrix

b=np.array([[1,2,3,4],[2,4,5,6]])
print(b)





#3D also called tensor

c=np.array([[[1,2,3],[4,5,6],[1,2,3]]])
print(c)

[[1 2 3 4]
 [2 4 5 6]]
[[[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [5]:








# dtype 
# helps to assign the array of desire data type 

new=np.array([1,2,3],dtype=float)
print(new)

[1. 2. 3.]


In [7]:






new=np.array([1,2,3],dtype=bool)
print(new)


[ True  True  True]


In [9]:





new=np.array([1,2,3],dtype=complex)
print(new)

[1.+0.j 2.+0.j 3.+0.j]


In [11]:








# creating numpy as arange 
a=np.arange(0,6)

print(a)

[0 1 2 3 4 5]


In [13]:




a=np.arange(1,6,2)
print(a)


[1 3 5]


In [15]:



# arange is frequently used with reshape 

b=np.arange(1,7).reshape(3,2)
print(b)


[[1 2]
 [3 4]
 [5 6]]


In [17]:





b=np.arange(1,11).reshape(2,5)
print(b)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [19]:






# initializing array with np.ones and np.zeros




a=np.ones((2,2))
print(a)


[[1. 1.]
 [1. 1.]]


In [21]:








b=np.zeros((4,5))
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [23]:






c=np.random.random((3,3))
print(c)


[[0.61270563 0.76168381 0.83612685]
 [0.86627436 0.19926354 0.46516623]
 [0.32255226 0.3979166  0.23626739]]


In [25]:








#np linearspace

a=np.linspace(2,15,8)
print(a)

[ 2.          3.85714286  5.71428571  7.57142857  9.42857143 11.28571429
 13.14285714 15.        ]


In [27]:







#np.identity


d=np.identity(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:









#array attributes 


# 1D or vector
a=np.arange(8)
print(a)


#2d or matrix
b=np.arange(10).reshape(2,5)
print(b)

#3d or tensor
c=np.arange(20).reshape(2,5,2)
print(c)


#8d
d=np.arange(256).reshape(2,2,2,2,2,2,2,2)
print(d)


[0 1 2 3 4 5 6 7]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
[[[[[[[[  0   1]
       [  2   3]]

      [[  4   5]
       [  6   7]]]


     [[[  8   9]
       [ 10  11]]

      [[ 12  13]
       [ 14  15]]]]



    [[[[ 16  17]
       [ 18  19]]

      [[ 20  21]
       [ 22  23]]]


     [[[ 24  25]
       [ 26  27]]

      [[ 28  29]
       [ 30  31]]]]]




   [[[[[ 32  33]
       [ 34  35]]

      [[ 36  37]
       [ 38  39]]]


     [[[ 40  41]
       [ 42  43]]

      [[ 44  45]
       [ 46  47]]]]



    [[[[ 48  49]
       [ 50  51]]

      [[ 52  53]
       [ 54  55]]]


     [[[ 56  57]
       [ 58  59]]

      [[ 60  61]
       [ 62  63]]]]]]





  [[[[[[ 64  65]
       [ 66  67]]

      [[ 68  69]
       [ 70  71]]]


     [[[ 72  73]
       [ 74  75]]

      [[ 76  77]
       [ 78  79]]]]



    [[[[ 80  81]
       [ 82  83]]

      [[ 84  85]
       [ 86  87]]]


     [[[ 88  89]
    

In [31]:



#ndim- no of dimensions of given array

# 1D or vector
a=np.arange(8)
print(a.ndim)


#2d or matrix
b=np.arange(10).reshape(2,5)
print(b.ndim)



1
2


In [33]:










#shape 
a.shape



b.shape   # 2 blocks 5 elements


(2, 5)

In [35]:
d.shape

(2, 2, 2, 2, 2, 2, 2, 2)

In [37]:






# size


d.size



256

In [39]:







#itemsize
a.itemsize


4

In [41]:




b.itemsize


4

In [43]:



#2d or matrix
b=np.arange(10,dtype=float).reshape(2,5)
print(b.itemsize)

8


In [45]:






#dtype

print(a.dtype)
b.dtype

int32


dtype('float64')

In [47]:




# changing datatype
c=np.arange(5)
print(c)

c.astype(np.int32)
c.dtype

[0 1 2 3 4]


dtype('int32')

In [9]:
#Array operations
import numpy as np

a=np.arange(1,13).reshape(4,3)
a




# scalart operations that is *,+,**,/




array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [13]:
a**2

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [15]:



# relational operations 
#>,<,==   here  each elemnts is compared 

a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:

a==5

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [21]:

# vector operations 
# shape should be equal and each elemnts is performmed according to its corresponding element 

a1=np.arange(1,11).reshape(2,5)
a2=np.arange(5,15).reshape(2,5)




a1+a2

array([[ 6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24]])

In [23]:



a1*a2

array([[  5,  12,  21,  32,  45],
       [ 60,  77,  96, 117, 140]])

In [25]:
a1==a2

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [39]:





# Array functions 

a1=np.random.random((3,3))
a1
a1=np.round(a1*100)
a1

array([[81., 45., 73.],
       [69., 83., 42.],
       [11., 82., 19.]])

In [41]:




# min,max, sum, prod 
# basically , it gives the result based on all elemnts present 
np.max(a1)

83.0

In [43]:
np.min(a1)

11.0

In [45]:
np.prod(a1)

1096874663165820.0

In [47]:
np.sum(a1)

505.0

In [49]:
# numpy gives the flexibility to perform the same functions  for row and column

#  axis define it row=1, coloumn=0



np.max(a1, axis=1)

array([81., 83., 82.])

In [51]:
np.min(a1, axis=0)

array([11., 45., 19.])

In [53]:



# mean, median,std, var    can be  calculated 

np.mean(a1)


56.111111111111114

In [57]:
np.mean(a1 ,axis=1)

array([66.33333333, 64.66666667, 37.33333333])

In [59]:
np.median(a1,axis=0)

array([69., 82., 42.])

In [63]:
np.std(a1,axis=0)

array([30.56504903, 17.68238295, 22.12590237])

In [65]:
np.var(a1)

688.7654320987655

In [71]:
# trignometric functions 
np.sin(a1)

array([[-0.62988799,  0.85090352, -0.67677196],
       [-0.11478481,  0.96836446, -0.91652155],
       [-0.99999021,  0.31322878,  0.14987721]])

In [75]:



# dot product 
# dot product rule is expalined in note .please refer to the note 

a1=np.arange(1,10).reshape(3,3)
a2=np.arange(11,23).reshape(3,4)
np.dot(a1,a2)

array([[ 98, 104, 110, 116],
       [233, 248, 263, 278],
       [368, 392, 416, 440]])

In [77]:





#log and exponents 

np.log(a2)

array([[2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176],
       [2.94443898, 2.99573227, 3.04452244, 3.09104245]])

In [79]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [97]:


# round , floor and ceil
# detailed describtion presented in note 

a3=np.random.random((3,2))
a3=a3*200


In [91]:
np.round(a3)

array([[111., 101.],
       [165., 134.],
       [197.,  68.]])

In [93]:
np.ceil(a3)

array([[112., 101.],
       [165., 135.],
       [198.,  69.]])

In [95]:
np.floor(a3)

array([[111., 100.],
       [164., 134.],
       [197.,  68.]])

In [117]:




# difficult but conceptual
# indexing and slicing

a1=np.arange(1,10) #1d
a2=np.arange(1,11).reshape(5,2) #2d
a3=np.arange(1,9).reshape(2,2,2)  #3d

In [107]:



# for 1d same as python 
a1[0]
a1[-1]




9

In [119]:
# for 2d 
a2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [127]:

# accessing 5 in 2d 
# [row,col]
a2[2,0]

5

In [129]:



# accesssing 10
a2[4,1]

10

In [131]:
# for 3d  tensor 
# basicallly 3d tensor is a collection of 2d tensor so to acess it first of all we have to find in which tensor it lies  then following the 

# same pattern what we have done for 2d



a3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [133]:



# accessing 8 in 3d
# [colloection of 2d tensor so which item it lies, then following the same pattern like 2d  tensor ]

a3[1,1,1]

8

In [135]:

# acessing 2
a3[0,0,1]

2

In [137]:




# slicing 
# for 1d
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
a1[0:6]

array([1, 2, 3, 4, 5, 6])

In [141]:
a1[4:8]

array([5, 6, 7, 8])

In [143]:




 # slicing for 2d
a2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [145]:
#[which row, how many columns ]

a2[0,:]

array([1, 2])

In [147]:
a2[:,0]

array([1, 3, 5, 7, 9])

In [149]:
a2[2:4,:]

array([[5, 6],
       [7, 8]])

In [155]:



a2[1:4:2,1]

array([4, 8])

In [175]:


# slicing for 3d array
a4=np.arange(18).reshape(3,2,3)
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [177]:


a4[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [179]:
a4[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [181]:

a4[0,1,:]


array([3, 4, 5])

In [183]:
a4[1,:,1]

array([ 7, 10])

In [185]:



a4[2,:,1:]

array([[13, 14],
       [16, 17]])

In [187]:


a4[2,0,0::2]

array([12, 14])

In [189]:



# iteration 



# for 1 dimensional

for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9


In [191]:




# for 2d 

for i  in a2:
    print(i)

[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [193]:



for i in a3:
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [195]:



for i in np.nditer(a3):   # it coverts 3d to 1d then print each items 
    print(i)

1
2
3
4
5
6
7
8


In [197]:



# reshape , tramspose and ravel


np.transpose(a2)

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [199]:



np.ravel(a3)  # convert any dimensional array to one dimensional


array([1, 2, 3, 4, 5, 6, 7, 8])

In [201]:



# stacking
a4=np.arange(1,11).reshape(2,5)
a5=np.arange(12,22).reshape(2,5)

In [203]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [205]:
a5

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [207]:



# vertical stacking
np.vstack((a4,a5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [209]:


# horizontal stacking
np.hstack((a4,a5))

array([[ 1,  2,  3,  4,  5, 12, 13, 14, 15, 16],
       [ 6,  7,  8,  9, 10, 17, 18, 19, 20, 21]])

In [213]:



# splitting 


# horizontal splitting 

np.hsplit(a5,5)


[array([[12],
        [17]]),
 array([[13],
        [18]]),
 array([[14],
        [19]]),
 array([[15],
        [20]]),
 array([[16],
        [21]])]

In [219]:


# vertical splitting 


np.vsplit(a4,2)


[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]